### PR TITLE
Rework printing information for FGLM and lifting of Gröbner bases

### PR DESCRIPTION
**Pull request by jerebertho**
The goal of this PR is to homogenize how information is printed in msolve with option -v. It takes as a template the printing of F4 and reproduces it in FGLM and the lifting of Gröbner bases over rational numbers.
Below I give examples of the output in the terminal.

For the moment, I set this PR as a draft for several reasons:

1. Do we want such a homogenized printing and so should this be done to real roots isolation as well?
2. Contrary to F4, the code does not completely rely on the md_t struct of src/neogb/data.h. Should this be corrected?
3. Some printing are sent onto stdout and some to stderr. Should this be homogenized or at least clear which stream is used for what?

Comments are welcome!

Call of msolve over rational numbers with option -P 2

```
--------------- INPUT DATA ---------------
#variables                       6
#equations                       6
#invalid equations               0
field characteristic             0
homogeneous input?               0
signature-based computation      0
monomial order                 DRL
basis hash table resetting     OFF
linear algebra option            2
initial hash table size     131072 (2^17)
max pair selection             ALL
reduce gb                        1
#threads                         1
info level                       2
generate pbm files               0
------------------------------------------

Legend for f4 information
--------------------------------------------------------
deg       current degree of pairs selected in this round
sel       number of pairs selected in this round
pairs     total number of pairs in pair list
mat       matrix dimensions (# rows x # columns)
density   density of the matrix
new data  # new elements for basis in this round
          # zero reductions during linear algebra
time(rd)  time of the current f4 round in seconds given
          for real and cpu time
--------------------------------------------------------

deg     sel   pairs        mat          density            new data         time(rd) in sec (real|cpu)
------------------------------------------------------------------------------------------------------
  2       2       4      12 x 28         23.21%        2 new       0 zero         0.00 | 0.00         
  3       5       5      43 x 68         12.18%        5 new       0 zero         0.00 | 0.00         
  4      16      16     102 x 122        10.51%        6 new      10 zero         0.00 | 0.00         
  5      23      23     142 x 154        10.80%        4 new      19 zero         0.00 | 0.00         
  6      16      16     126 x 142        12.03%        1 new      15 zero         0.00 | 0.00         
  7       4       4     107 x 134        12.28%        0 new       4 zero         0.00 | 0.00         
------------------------------------------------------------------------------------------------------
reduce final basis       25 x 57         36.98%       22 new       0 zero         0.00 | 0.00         
------------------------------------------------------------------------------------------------------

---------------- TIMINGS ----------------
overall(elapsed)        0.00 sec
overall(cpu)            0.00 sec
select                  0.00 sec   8.7%
symbolic prep.          0.00 sec  13.1%
update                  0.00 sec  27.8%
convert                 0.00 sec  15.3%
linear algebra          0.00 sec  13.1%
reduce gb               0.00 sec   0.0%
-----------------------------------------

---------- COMPUTATIONAL DATA -----------
size of basis                    22
#terms in basis                 528
#pairs reduced                   66
#GM criterion                   210
#redundant elements               2
#rows reduced                   154
#zero reductions                 48
max. matrix data                142 x 154 (10.797%)
max. symbolic hash table size  2^11
max. basis hash table size     2^16
-----------------------------------------

Learning phase 0.00 Gops/sec

fglm steps                                               time(rd) in sec (real|cpu)
------------------------------------------------------------------------------------------------------
multiplication matrix                                          0.00 | 0.00         
scalar sequence                                                0.00 | 0.00         
elimination polynomial                                         0.00 | 0.00         
parametrizations                                               0.00 | 0.00         
------------------------------------------------------------------------------------------------------

---------------- TIMINGS ----------------
overall(elapsed)        0.00 sec
overall(cpu)            0.00 sec
-----------------------------------------

---------- COMPUTATIONAL DATA -----------
degree of ideal                  32
#dense rows                      11
#normal forms                     0
total density                    89.2%
density of the free part         89.2%
deg. elim. pol.                  32
deg. sqfr. elim. pol.            32
-----------------------------------------


---------------- TIMINGS ----------------
multi-mod overall(elapsed)      0.00 sec
multi-mod F4                    0.00 sec
multi-mod FGLM                  0.00 sec
application phase          0.00 Gops/sec
-----------------------------------------

multi-modular steps
------------------------------------------------------------------------------------------------------
[0][1][2][3][4][5]{2}{4}{8}
------------------------------------------------------------------------------------------------------

---------- COMPUTATIONAL DATA -----------
#primes                           8
#bad primes                       0
-----------------------------------------

---------------- TIMINGS ----------------
CRT and ratrecon(elapsed)       0.00 sec
-----------------------------------------

---------------- TIMINGS ----------------
rational param(elapsed)         0.01 sec
rational param(cpu)             0.01 sec
-----------------------------------------


------------------------------------------------------------------------------------
msolve overall time           0.01 sec (elapsed) /  0.01 sec (cpu)
------------------------------------------------------------------------------------
```

Call of msolve over rational numbers with option -g 2

```

--------------- INPUT DATA ---------------
#variables                       6
#equations                       6
#invalid equations               0
field characteristic             0
homogeneous input?               0
signature-based computation      0
monomial order                 DRL
basis hash table resetting     OFF
linear algebra option            2
initial hash table size     131072 (2^17)
max pair selection             ALL
reduce gb                        1
#threads                         1
info level                       2
generate pbm files               0
------------------------------------------

Legend for f4 information
--------------------------------------------------------
deg       current degree of pairs selected in this round
sel       number of pairs selected in this round
pairs     total number of pairs in pair list
mat       matrix dimensions (# rows x # columns)
density   density of the matrix
new data  # new elements for basis in this round
          # zero reductions during linear algebra
time(rd)  time of the current f4 round in seconds given
          for real and cpu time
--------------------------------------------------------

deg     sel   pairs        mat          density            new data         time(rd) in sec (real|cpu)
------------------------------------------------------------------------------------------------------
  2       2       4      12 x 28         23.21%        2 new       0 zero         0.00 | 0.00         
  3       5       5      43 x 68         12.18%        5 new       0 zero         0.00 | 0.00         
  4      16      16     102 x 122        10.51%        6 new      10 zero         0.00 | 0.00         
  5      23      23     142 x 154        10.80%        4 new      19 zero         0.00 | 0.00         
  6      16      16     126 x 142        12.03%        1 new      15 zero         0.00 | 0.00         
  7       4       4     107 x 134        12.28%        0 new       4 zero         0.00 | 0.00         
------------------------------------------------------------------------------------------------------
reduce final basis       25 x 57         36.98%       22 new       0 zero         0.00 | 0.00         
------------------------------------------------------------------------------------------------------

---------------- TIMINGS ----------------
overall(elapsed)        0.00 sec
overall(cpu)            0.00 sec
select                  0.00 sec   9.5%
symbolic prep.          0.00 sec  13.4%
update                  0.00 sec  28.3%
convert                 0.00 sec  13.1%
linear algebra          0.00 sec  13.6%
reduce gb               0.00 sec   0.0%
-----------------------------------------

---------- COMPUTATIONAL DATA -----------
size of basis                    22
#terms in basis                 528
#pairs reduced                   66
#GM criterion                   210
#redundant elements               2
#rows reduced                   154
#zero reductions                 48
max. matrix data                142 x 154 (10.797%)
max. symbolic hash table size  2^11
max. basis hash table size     2^16
-----------------------------------------

Learning phase 0.00 Gops/sec


---------- COMPUTATIONAL DATA -----------
[1][5][5][6][4][1]
#polynomials to lift             22
-----------------------------------------

---------------- TIMINGS ----------------
multi-mod overall(elapsed)      0.00 sec
application phase          0.00 Gops/sec
-----------------------------------------

multi-modular steps
------------------------------------------------------------------------------------------------------
{1}{2}<40.91%><90.91%>{4}<100.00%> 
------------------------------------------------------------------------------------------------------


---------- COMPUTATIONAL DATA -----------
Max coeff. bitsize               62
#primes                           6
#bad primes                       0
-----------------------------------------

---------------- TIMINGS ----------------
CRT     (elapsed)               0.00 sec
ratrecon(elapsed)               0.00 sec
-----------------------------------------


------------------------------------------------------------------------------------
msolve overall time           0.01 sec (elapsed) /  0.01 sec (cpu)
------------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by ederc** [comment]
I like that very much, thanks @jerebertho.

**Comment by mohabsafey** [comment]
Me too ; it is much better like this ; many thanks

**Comment by ederc** [comment]
I would propose to merge this PR soon. About using `md_t` and fixing the streams used we need to have a bigger discussion on how to restructure not only these parts of the code base.

**Comment by jerebertho** [comment]
> I would propose to merge this PR soon. About using `md_t` and fixing the streams used we need to have a bigger discussion on how to restructure not only these parts of the code base.

I agree about `md_t` and the streams. I just mentioned it so that we put this question on our todolist :-). I will rebase from v0.6.8. Then, anyone can merge.

**Pull request merged**
