### PR TITLE
Handle input file line endings

### PR DESCRIPTION
**Pull request by vneiger**
This solves #182.

This also does minor cleaning in two functions of iofiles, the only difference in behaviour should be that `get_nvars` returns `-1` on failure (it used to return 0).

Before merging: related to the FIXME's I put in `get_data_from_file`, shouldn't this function fail as soon as one of its "data retrieval" components fail?

Also, in this function, is it really necessary to allocate 1073741824 bytes (1GB) for `line`? I assume only a very small part of it will ever be used so it will sit mostly in virtual memory, but still... say we read line by line using getline (which is not exactly the case currently), we could simply let getline do the necessary reallocs.

### CODE REVIEW

**Comment by mohabsafey** [comment]
If we go for this, could you add some tests?

**Comment by vneiger** [comment]
Sure! I'll work on it and let you know.

**Comment by vneiger** [comment]
Let's wait for CI to complete, but up to some minor fix, but this now should work with several tests added (3 files with DOS endings ; 1 file with DOS endings + no end of line in last line). In case this can be re-used: this contains a function that tests that two `data_gens_ff_t` contain the same data.

**Comment by ederc** [comment]
> but up to some minor fix,

@vneiger So is this ready to be merged or do we expect some fix?

**Pull request merged**
